### PR TITLE
Added PersonModel for non-web logging

### PR DESCRIPTION
**Pull request by Atrejoe**
Obtained user information from the environment

### CODE REVIEW

**Comment by richardversluis** [comment]
This is interesting, but I'm worried this a bit confusing in web-usage when working with threads / tasks, situations where there isn't a `HttpContext.Current`. You'll get a mix of real users and webserver(s) in Rollbar under the People tab. 

It would be perfect if we could detect we're using Rollbar in a desktop application (I think this is your usecase?). A empty `HttpContext.Current` doesn't mean we aren't using Rollbar in a webapplication.

**Comment by Atrejoe** [comment]
You are right about the possible confusion.
Maybe we could base it in a aptly named configuration switch?
Shall I make a proposal?

On detection of a desktop environment, do you have any suggestions?

On Mar 6, 2016 12:11 PM, Richard Versluis <notifications@github.com> wrote:

This is interesting, but I'm worried this a bit confusing in web-usage when working with threads / tasks, situations where there isn't a HttpContext.Current. You'll get a mix of real users and webserver(s) in Rollbar under the People tab. 

It would be perfect if we could detect we're using Rollbar in a desktop application (I think this is your usecase?). A empty HttpContext.Current doesn't mean we aren't using Rollbar in a webapplication.

**Comment by richardversluis** [comment]
Maybe something like this?

http://stackoverflow.com/questions/3179716/how-determine-if-application-is-web-application

```csharp
HostingEnvironment.IsHosted
```

**Comment by Atrejoe** [comment]
I added the clause detecting wether the application is in a hosted environment.

_The mentioned overhead is already present, as this component already references `System.Web`._

**Pull request merged**
